using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.FindSymbols;
using Microsoft.CodeAnalysis.Operations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;

namespace CodeJanitor.Logic.Transformations;

/// <summary>
/// Adds the <c>sealed</c> modifier to the top-level classes and record classes of a C# file that the semantic model
/// proves are neither designed nor used for inheritance anywhere in the solution.
/// </summary>
/// <remarks>
/// A class is sealed only when all of these hold:
/// <list type="bullet">
/// <item>it is not already sealed, abstract, static or partial;</item>
/// <item>it declares no virtual or abstract member;</item>
/// <item>it declares no <c>protected</c>, <c>protected internal</c> or <c>private protected</c> member, constructors,
/// accessors, fields and nested types included (overrides excepted): such members only make sense for derived
/// classes, and sealing would report CS0628;</item>
/// <item>no class of the solution derives from it;</item>
/// <item>no generic type constraint of the solution names it (a sealed type in a constraint is CS0701);</item>
/// <item>no cast, <c>as</c>, <c>is</c>, type pattern, <c>case</c> type label, <c>foreach</c> or reference equality
/// (<c>==</c>, <c>!=</c>) of the solution converts it to or from an interface it does not implement, directly or as an
/// array element, a tuple element or a covariant delegate type argument (sealing removes that explicit conversion);</item>
/// <item>its declaration, leading trivia included, contains no code excluded by a preprocessor directive, and no such
/// code of the solution names it (the semantic model cannot see inactive code, which other build configurations
/// compile);</item>
/// <item>no project written in another language than C# references its project (the checks above only read C#).</item>
/// </list>
/// A file compiled by several projects or target frameworks is analyzed in each of them, and a class is sealed only
/// when it is safe in every one. Classes outside the solution (other repositories, published packages) cannot be
/// seen: sealing a public class remains an API change, which is why the cleanup setting is an explicit opt-in.
/// The scans that cover the whole solution are cached by what they read, not by solution snapshot: the conversion
/// sites of a project by its first syntax tree and the version of the project and of the projects it references, the
/// inactive code of a file by its syntax tree. A syntax tree is shared by every snapshot in which its document did not
/// change, and the version changes with any change of the project or of a project it references, so a batch of files
/// rescans only what a rewritten file changed; entries are released with their tree. Documents generated by source
/// generators are scanned like written ones. Pure logic over Roslyn workspace types, unit-testable without Visual
/// Studio.
/// </remarks>
public sealed class ClassSealingConverter
{
    /// <summary>
    /// The classes each project converts explicitly with interfaces, keyed by the first syntax tree of the project.
    /// </summary>
    private readonly AsyncCache<SyntaxTree, ConvertedClasses> _convertedClasses = new AsyncCache<SyntaxTree, ConvertedClasses>();

    /// <summary>
    /// The identifiers in the inactive code of each syntax tree that has directives, released with the tree.
    /// </summary>
    private readonly ConditionalWeakTable<SyntaxTree, HashSet<string>> _inactiveCodeIdentifiers = new ConditionalWeakTable<SyntaxTree, HashSet<string>>();

    /// <summary>
    /// Seals the classes of the file that are safe to seal in every document of <paramref name="documents" />.
    /// </summary>
    /// <param name="documents">The documents of one file, one per project flavor compiling it, all with the same text.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The text of the file with the safe classes sealed, or its unchanged text when none is.</returns>
    public async Task<string> SealWhenSafeAsync(IReadOnlyList<Document> documents, CancellationToken cancellationToken)
    {
        if (documents is null || documents.Count == 0)
        {
            throw new ArgumentException("At least one document is required.", nameof(documents));
        }

        var root = await documents[0].GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
        var candidates = GetCandidates(root).Select(declaration => declaration.SpanStart).ToList();

        foreach (var document in documents)
        {
            if (candidates.Count == 0)
            {
                break;
            }

            var safeInDocument = await GetSafeToSealAsync(document, cancellationToken).ConfigureAwait(false);
            candidates.RemoveAll(position => !safeInDocument.Contains(position));
        }

        if (candidates.Count == 0)
        {
            return root.ToFullString();
        }

        var toSeal = GetCandidates(root).Where(declaration => candidates.Contains(declaration.SpanStart)).ToList();

        return root.ReplaceNodes(toSeal, (original, _) => WithSealedModifier(original)).ToFullString();
    }

    /// <summary>
    /// Gets the start positions of the candidate declarations of <paramref name="document" /> that are safe to seal
    /// in its project.
    /// </summary>
    private async Task<HashSet<int>> GetSafeToSealAsync(Document document, CancellationToken cancellationToken)
    {
        var solution = document.Project.Solution;
        if (solution.GetProjectDependencyGraph().GetProjectsThatTransitivelyDependOnThisProject(document.Project.Id)
            .Any(projectId => solution.GetProject(projectId)?.Language != LanguageNames.CSharp))
        {
            return new HashSet<int>();
        }

        var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
        var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
        var inactiveIdentifiers = await GetInactiveCodeIdentifiersAsync(solution, cancellationToken).ConfigureAwait(false);
        var sealable = new Dictionary<INamedTypeSymbol, int>(SymbolEqualityComparer.Default);

        foreach (var declaration in GetCandidates(root))
        {
            if (!ContainsInactiveCode(declaration) &&
                semanticModel.GetDeclaredSymbol(declaration, cancellationToken) is INamedTypeSymbol type &&
                !inactiveIdentifiers.Contains(type.Name) &&
                IsDeclaredForSealing(type) &&
                !await IsInheritedOrConstrainedAsync(type, solution, cancellationToken).ConfigureAwait(false))
            {
                sealable[type] = declaration.SpanStart;
            }
        }

        if (sealable.Count > 0)
        {
            var converted = await GetExplicitlyConvertedWithInterfacesAsync(sealable.Keys.ToList(), document.Project, cancellationToken).ConfigureAwait(false);
            foreach (var type in converted)
            {
                sealable.Remove(type);
            }
        }

        return new HashSet<int>(sealable.Values);
    }

    /// <summary>
    /// Gets the classes that explicit conversion sites of <paramref name="project" /> convert to or from an interface
    /// they do not implement (see <see cref="ConvertedClasses" />), or null when the project has no C# compilation.
    /// The same object is returned for every snapshot in which the project and the projects it references did not
    /// change.
    /// </summary>
    internal async Task<ConvertedClasses> GetConvertedClassesAsync(Project project, CancellationToken cancellationToken)
    {
        if (!(await project.GetCompilationAsync(cancellationToken).ConfigureAwait(false) is CSharpCompilation compilation))
        {
            return null;
        }

        var firstDocument = project.Documents.FirstOrDefault();
        var firstTree = firstDocument is null ? null : await firstDocument.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);
        if (firstTree is null)
        {
            return await FindConvertedClassesAsync(compilation, cancellationToken).ConfigureAwait(false);
        }

        var version = await project.GetDependentVersionAsync(cancellationToken).ConfigureAwait(false);

        return await _convertedClasses.GetOrComputeAsync(firstTree, version, token => FindConvertedClassesAsync(compilation, token), cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Gets the identifiers that occur in code excluded by a preprocessor directive anywhere in the solution. Such code
    /// is compiled in other build configurations and may derive from, constrain or convert a class the semantic model
    /// sees as safe to seal.
    /// </summary>
    internal async Task<HashSet<string>> GetInactiveCodeIdentifiersAsync(Solution solution, CancellationToken cancellationToken)
    {
        var identifiers = new HashSet<string>(StringComparer.Ordinal);

        foreach (var project in solution.Projects)
        {
            foreach (var document in await GetDocumentsWithGeneratedAsync(project, cancellationToken).ConfigureAwait(false))
            {
                var tree = await document.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);
                var root = tree is null ? null : await tree.GetRootAsync(cancellationToken).ConfigureAwait(false);
                if (root is null || !root.ContainsDirectives)
                {
                    continue;
                }

                identifiers.UnionWith(_inactiveCodeIdentifiers.GetValue(tree, _ => FindInactiveCodeIdentifiers(root)));
            }
        }

        return identifiers;
    }

    /// <summary>
    /// Gets the documents of the project, and those its source generators add to the compilation.
    /// </summary>
    private static async Task<IEnumerable<Document>> GetDocumentsWithGeneratedAsync(Project project, CancellationToken cancellationToken) =>
        project.Documents.Concat(await project.GetSourceGeneratedDocumentsAsync(cancellationToken).ConfigureAwait(false));

    /// <summary>
    /// Determines whether the declaration, its leading trivia included, contains code excluded by a preprocessor
    /// directive (<c>#if</c>/<c>#elif</c>/<c>#else</c> branches inactive in this project flavor). The semantic model
    /// cannot see that code, which other build configurations compile and which may declare modifiers or members that
    /// forbid sealing.
    /// </summary>
    private static bool ContainsInactiveCode(TypeDeclarationSyntax declaration) =>
        declaration.DescendantTrivia(descendIntoTrivia: true)
            .Any(trivia => trivia.IsKind(SyntaxKind.DisabledTextTrivia));

    /// <summary>
    /// Gets the identifiers that occur in the code of <paramref name="root" /> excluded by a preprocessor directive.
    /// </summary>
    private static HashSet<string> FindInactiveCodeIdentifiers(SyntaxNode root)
    {
        var identifiers = new HashSet<string>(StringComparer.Ordinal);

        foreach (var trivia in root.DescendantTrivia(descendIntoTrivia: true))
        {
            if (!trivia.IsKind(SyntaxKind.DisabledTextTrivia))
            {
                continue;
            }

            foreach (var token in SyntaxFactory.ParseTokens(trivia.ToString()))
            {
                if (token.IsKind(SyntaxKind.IdentifierToken))
                {
                    identifiers.Add(token.ValueText);
                }
            }
        }

        return identifiers;
    }

    /// <summary>
    /// Gets the top-level class and record class declarations that the modifiers written on them allow to seal.
    /// </summary>
    private static IEnumerable<TypeDeclarationSyntax> GetCandidates(SyntaxNode root) =>
        root.DescendantNodes(node => node is CompilationUnitSyntax || node is BaseNamespaceDeclarationSyntax)
            .OfType<TypeDeclarationSyntax>()
            .Where(declaration =>
                (declaration is ClassDeclarationSyntax ||
                 (declaration is RecordDeclarationSyntax record && !record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword))) &&
                !declaration.Modifiers.Any(modifier =>
                    modifier.IsKind(SyntaxKind.SealedKeyword) ||
                    modifier.IsKind(SyntaxKind.AbstractKeyword) ||
                    modifier.IsKind(SyntaxKind.StaticKeyword) ||
                    modifier.IsKind(SyntaxKind.PartialKeyword)));

    /// <summary>
    /// Determines whether the members the class declares show it is not designed for inheritance. Members the compiler
    /// declares implicitly (for example the virtual equality members of a record) are ignored: sealing adjusts them.
    /// </summary>
    private static bool IsDeclaredForSealing(INamedTypeSymbol type)
    {
        if (type.TypeKind != TypeKind.Class || type.IsSealed || type.IsAbstract || type.IsStatic || type.DeclaringSyntaxReferences.Length != 1)
        {
            return false;
        }

        return !type.GetMembers().Any(member =>
            !member.IsImplicitlyDeclared &&
            (member.IsVirtual || member.IsAbstract || (!member.IsOverride && IsProtected(member.DeclaredAccessibility))));
    }

    private static bool IsProtected(Accessibility accessibility) =>
        accessibility == Accessibility.Protected ||
        accessibility == Accessibility.ProtectedOrInternal ||
        accessibility == Accessibility.ProtectedAndInternal;

    /// <summary>
    /// Determines whether a class of the solution derives from <paramref name="type" /> or a generic type constraint of
    /// the solution names it.
    /// </summary>
    private static async Task<bool> IsInheritedOrConstrainedAsync(INamedTypeSymbol type, Solution solution, CancellationToken cancellationToken)
    {
        var derived = await SymbolFinder.FindDerivedClassesAsync(type, solution, transitive: false, cancellationToken: cancellationToken).ConfigureAwait(false);
        if (derived.Any())
        {
            return true;
        }

        var references = await SymbolFinder.FindReferencesAsync(type, solution, cancellationToken).ConfigureAwait(false);
        foreach (var location in references.SelectMany(reference => reference.Locations))
        {
            var referenceRoot = await location.Document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
            var node = referenceRoot.FindNode(location.Location.SourceSpan, getInnermostNodeForTie: true);
            if (node.AncestorsAndSelf().Any(ancestor => ancestor is TypeConstraintSyntax))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Gets the <paramref name="candidates" /> that an explicit conversion site of <paramref name="project" /> or of a
    /// project depending on it converts to or from an interface the class does not implement. That explicit reference
    /// conversion exists only while the class is not sealed: sealing would report CS0030, CS0039, CS0019 or CS8121, or
    /// turn an <c>is</c> test into CS0184.
    /// </summary>
    private async Task<List<INamedTypeSymbol>> GetExplicitlyConvertedWithInterfacesAsync(
        IReadOnlyCollection<INamedTypeSymbol> candidates,
        Project project,
        CancellationToken cancellationToken)
    {
        var solution = project.Solution;
        var projectIds = new List<ProjectId> { project.Id };
        projectIds.AddRange(solution.GetProjectDependencyGraph().GetProjectsThatTransitivelyDependOnThisProject(project.Id));
        var converted = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var scanned in projectIds.Select(solution.GetProject).Where(scanned => scanned?.Language == LanguageNames.CSharp))
        {
            var conversions = await GetConvertedClassesAsync(scanned, cancellationToken).ConfigureAwait(false);
            if (conversions is null)
            {
                continue;
            }

            foreach (var candidate in candidates.Where(candidate => !converted.Contains(candidate)))
            {
                // The candidate as seen by the compilation of the scanned project.
                var similar = SymbolFinder.FindSimilarSymbols(candidate, conversions.Compilation, cancellationToken).FirstOrDefault();
                if (similar is not null && conversions.Classes.Contains(similar.OriginalDefinition))
                {
                    converted.Add(candidate);
                }
            }
        }

        return converted.ToList();
    }

    /// <summary>
    /// Gets the classes (original definitions) that an explicit conversion site of <paramref name="compilation" />
    /// converts to or from an interface they do not implement. The trees of the compilation include those of the
    /// source generators, and the result depends on nothing else, which is what makes it cacheable by compilation.
    /// </summary>
    private static async Task<ConvertedClasses> FindConvertedClassesAsync(CSharpCompilation compilation, CancellationToken cancellationToken)
    {
        var classes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var tree in compilation.SyntaxTrees)
        {
            var root = await tree.GetRootAsync(cancellationToken).ConfigureAwait(false);
            SemanticModel semanticModel = null;

            foreach (var node in root.DescendantNodes())
            {
                if (!IsExplicitConversionSite(node))
                {
                    continue;
                }

                semanticModel ??= compilation.GetSemanticModel(tree);
                var (source, target) = GetConversionTypes(node, semanticModel, cancellationToken);
                AddClassesConvertedWithInterfaces(source, target, compilation, classes);
            }
        }

        return new ConvertedClasses(compilation, classes);
    }

    private static bool IsExplicitConversionSite(SyntaxNode node) =>
        node is CastExpressionSyntax ||
        node is PatternSyntax ||
        node is CaseSwitchLabelSyntax ||
        node is ForEachStatementSyntax ||
        node.IsKind(SyntaxKind.AsExpression) ||
        node.IsKind(SyntaxKind.IsExpression) ||
        node.IsKind(SyntaxKind.EqualsExpression) ||
        node.IsKind(SyntaxKind.NotEqualsExpression);

    /// <summary>
    /// Gets the type converted from and the type converted to at an explicit conversion site (for a reference
    /// equality, the types of its operands, one of which the other must convert to).
    /// </summary>
    private static (ITypeSymbol Source, ITypeSymbol Target) GetConversionTypes(SyntaxNode node, SemanticModel semanticModel, CancellationToken cancellationToken)
    {
        switch (node)
        {
            case CastExpressionSyntax cast:
                return (semanticModel.GetTypeInfo(cast.Expression, cancellationToken).Type, semanticModel.GetTypeInfo(cast.Type, cancellationToken).Type);

            case BinaryExpressionSyntax equality when equality.IsKind(SyntaxKind.EqualsExpression) || equality.IsKind(SyntaxKind.NotEqualsExpression):
                return semanticModel.GetOperation(equality, cancellationToken) is IBinaryOperation { OperatorMethod: null }
                    ? (semanticModel.GetTypeInfo(equality.Left, cancellationToken).Type, semanticModel.GetTypeInfo(equality.Right, cancellationToken).Type)
                    : (null, null);
            case BinaryExpressionSyntax binary:
                return (semanticModel.GetTypeInfo(binary.Left, cancellationToken).Type, semanticModel.GetTypeInfo(binary.Right, cancellationToken).Type);

            case ForEachStatementSyntax forEach:
                return (semanticModel.GetForEachStatementInfo(forEach).ElementType, semanticModel.GetTypeInfo(forEach.Type, cancellationToken).Type);

            case PatternSyntax pattern when semanticModel.GetOperation(pattern, cancellationToken) is IPatternOperation operation:
                return (operation.InputType, operation.NarrowedType);

            case CaseSwitchLabelSyntax label when label.Parent?.Parent is SwitchStatementSyntax switchStatement &&
                                                  semanticModel.GetSymbolInfo(label.Value, cancellationToken).Symbol is ITypeSymbol type:
                return (semanticModel.GetTypeInfo(switchStatement.Expression, cancellationToken).Type, type);

            default:
                return (null, null);
        }
    }

    /// <summary>
    /// Adds to <paramref name="classes" /> the class that the conversion converts to or from an interface the class does
    /// not implicitly convert to, a conversion that sealing the class removes. The conversion is followed into array
    /// elements (also against the type argument of the generic interface a one-dimensional array implements, such as
    /// <c>IList&lt;T&gt;</c>), tuple elements and covariant type arguments of the same generic delegate, which convert
    /// only when their types do (interfaces and contravariant type arguments convert explicitly whatever the class).
    /// </summary>
    private static void AddClassesConvertedWithInterfaces(ITypeSymbol source, ITypeSymbol target, CSharpCompilation compilation, HashSet<INamedTypeSymbol> classes)
    {
        if (source is null || target is null)
        {
            return;
        }

        if (source is IArrayTypeSymbol sourceArray && target is IArrayTypeSymbol targetArray)
        {
            AddClassesConvertedWithInterfaces(sourceArray.ElementType, targetArray.ElementType, compilation, classes);

            return;
        }

        if (source is IArrayTypeSymbol arrayToInterface && TryGetImplementedTypeArgument(arrayToInterface, target, out ITypeSymbol interfaceElement))
        {
            AddClassesConvertedWithInterfaces(arrayToInterface.ElementType, interfaceElement, compilation, classes);

            return;
        }

        if (target is IArrayTypeSymbol interfaceToArray && TryGetImplementedTypeArgument(interfaceToArray, source, out interfaceElement))
        {
            AddClassesConvertedWithInterfaces(interfaceElement, interfaceToArray.ElementType, compilation, classes);

            return;
        }

        if (!(source is INamedTypeSymbol sourceType) || !(target is INamedTypeSymbol targetType))
        {
            return;
        }

        if (sourceType.IsTupleType && targetType.IsTupleType)
        {
            if (sourceType.TupleElements.Length == targetType.TupleElements.Length)
            {
                for (var index = 0; index < sourceType.TupleElements.Length; index++)
                {
                    AddClassesConvertedWithInterfaces(sourceType.TupleElements[index].Type, targetType.TupleElements[index].Type, compilation, classes);
                }
            }

            return;
        }

        if (sourceType.TypeKind == TypeKind.Delegate && sourceType.IsGenericType &&
            SymbolEqualityComparer.Default.Equals(sourceType.OriginalDefinition, targetType.OriginalDefinition))
        {
            var typeParameters = sourceType.OriginalDefinition.TypeParameters;
            for (var index = 0; index < typeParameters.Length; index++)
            {
                if (typeParameters[index].Variance == VarianceKind.Out)
                {
                    AddClassesConvertedWithInterfaces(sourceType.TypeArguments[index], targetType.TypeArguments[index], compilation, classes);
                }
            }

            return;
        }

        if (targetType.TypeKind == TypeKind.Interface && sourceType.TypeKind == TypeKind.Class &&
            !compilation.ClassifyConversion(sourceType, targetType).IsImplicit)
        {
            classes.Add(sourceType.OriginalDefinition);
        }
        else if (sourceType.TypeKind == TypeKind.Interface && targetType.TypeKind == TypeKind.Class &&
                 !compilation.ClassifyConversion(targetType, sourceType).IsImplicit)
        {
            classes.Add(targetType.OriginalDefinition);
        }
    }

    /// <summary>
    /// Whether <paramref name="type" /> is a generic interface with one type argument that the one-dimensional
    /// <paramref name="array" /> implements (<c>IList&lt;T&gt;</c>, <c>IReadOnlyList&lt;T&gt;</c>, ...), and that type
    /// argument.
    /// </summary>
    private static bool TryGetImplementedTypeArgument(IArrayTypeSymbol array, ITypeSymbol type, out ITypeSymbol typeArgument)
    {
        typeArgument = null;
        if (array.Rank != 1 || !(type is INamedTypeSymbol { TypeKind: TypeKind.Interface, IsGenericType: true, TypeArguments.Length: 1 } named))
        {
            return false;
        }

        foreach (INamedTypeSymbol implemented in array.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(implemented.OriginalDefinition, named.OriginalDefinition))
            {
                typeArgument = named.TypeArguments[0];

                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Adds a sealed modifier to the given type declaration.
    /// </summary>
    private static TypeDeclarationSyntax WithSealedModifier(TypeDeclarationSyntax typeDecl)
    {
        var sealedToken = SyntaxFactory.Token(SyntaxKind.SealedKeyword).WithTrailingTrivia(SyntaxFactory.Space);

        if (typeDecl.Modifiers.Count == 0)
        {
            sealedToken = sealedToken.WithLeadingTrivia(typeDecl.Keyword.LeadingTrivia);
            var newKeyword = typeDecl.Keyword.WithLeadingTrivia(SyntaxTriviaList.Empty);

            return typeDecl.WithModifiers(SyntaxFactory.TokenList(sealedToken)).WithKeyword(newKeyword);
        }

        return typeDecl.WithModifiers(typeDecl.Modifiers.Add(sealedToken));
    }

    /// <summary>
    /// The classes a project converts explicitly with interfaces, as symbols of <see cref="Compilation" />.
    /// </summary>
    internal sealed class ConvertedClasses
    {
        public ConvertedClasses(CSharpCompilation compilation, HashSet<INamedTypeSymbol> classes)
        {
            Compilation = compilation;
            Classes = classes;
        }

        public CSharpCompilation Compilation { get; }

        public HashSet<INamedTypeSymbol> Classes { get; }
    }

    /// <summary>
    /// The values computed for keys and versions, at most once at a time and released with the key. The entry of a key
    /// holds the value of one version: a call with another version replaces it. A computation that fails or is
    /// canceled is not kept: the next call computes it again.
    /// </summary>
    internal sealed class AsyncCache<TKey, TValue>
        where TKey : class
    {
        private readonly object _gate = new object();
        private readonly ConditionalWeakTable<TKey, Entry> _entries = new ConditionalWeakTable<TKey, Entry>();

        /// <summary>
        /// Gets the value of <paramref name="key" /> at <paramref name="version" />, computing it with
        /// <paramref name="computeAsync" /> when no call has computed it or is computing it. Callers arriving during the
        /// computation wait for it; when it is canceled by the token of the caller that runs it, a waiter whose own
        /// token is not canceled computes the value itself.
        /// </summary>
        /// <param name="key">The key.</param>
        /// <param name="version">The version of what the value is computed from.</param>
        /// <param name="computeAsync">Computes the value with the token of the calling computation.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>The value.</returns>
        public async Task<TValue> GetOrComputeAsync(TKey key, VersionStamp version, Func<CancellationToken, Task<TValue>> computeAsync, CancellationToken cancellationToken)
        {
            while (true)
            {
                var completion = new TaskCompletionSource<TValue>(TaskCreationOptions.RunContinuationsAsynchronously);
                var candidate = new Entry(version, completion.Task);
                Entry entry;
                lock (_gate)
                {
                    if (!_entries.TryGetValue(key, out entry) || entry.Version != version)
                    {
                        _entries.Remove(key);
                        _entries.Add(key, candidate);
                        entry = candidate;
                    }
                }

                if (entry == candidate)
                {
                    try
                    {
                        var value = await computeAsync(cancellationToken).ConfigureAwait(false);
                        completion.SetResult(value);

                        return value;
                    }
                    catch (Exception ex)
                    {
                        lock (_gate)
                        {
                            if (_entries.TryGetValue(key, out var current) && current == entry)
                            {
                                _entries.Remove(key);
                            }
                        }

                        if (ex is OperationCanceledException)
                        {
                            completion.SetCanceled();
                        }
                        else
                        {
                            completion.SetException(ex);
                        }

                        throw;
                    }
                }

                try
                {
                    return await entry.Completion.ConfigureAwait(false);
                }
                catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
                {
                    // Canceled by the token of the caller computing it: compute again with this one.
                }
            }
        }

        private sealed class Entry
        {
            public Entry(VersionStamp version, Task<TValue> completion)
            {
                Version = version;
                Completion = completion;
            }

            public VersionStamp Version { get; }

            public Task<TValue> Completion { get; }
        }
    }
}
